
services:
  backend:
    build: .
    ports:
      - "2049:8000  # Backend port, inspired by the year Blade Runner 2049 takes place"
    volumes:
      - ./data:/app/data:ro  # Mount the data folder for parsing (read-only access to enhance security)
    depends_on:
      - database
    env_file:
      - ./backend.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: postgres:16
    env_file:
      - ./database.env
    volumes:
      - datapunk_db_data:/var/lib/postgresql/data  # Use named volume to persist database data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./datapunk-frontend
      dockerfile: Dockerfile
    ports:
      - "2077:3000  # Frontend port, inspired by the Cyberpunk 2077 setting"
    restart: always

volumes:
  datapunk_db_data: