version: '3.10'

services:
  backend:
    build: .
    volumes:
      - ./data:/app/data:ro  # Mount the data folder for parsing (read-only access to enhance security)
    depends_on:
      - database
    env_file:
      - ./backend.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://database:5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: postgres:16
    env_file:
      - ./database.env
    volumes:
      - datapunk_db_data:/var/lib/postgresql/data  # Use named volume to persist database data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  datapunk_db_data: