openapi: 3.1.0
info:
  title: Marvin API - Authentication and Setup
  description: This is the core API setup for token-based authentication and server details for Marvin. All other functionality depends on this setup.
  version: 1.0.0

servers:
  - url: https://hungry-eels-type.loca.lt
    description: Marvin API Server exposed through LocalTunnel

components:
  securitySchemes:
    Full_Access_Token:
      type: apiKey
      in: header
      name: X-Full-Access-Token
      description: Full Access Token for all Marvin API operations.
  
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          description: The email of the Marvin user.
          example: user@example.com
        username:
          type: string
          description: The username of the Marvin user.
          example: marvinuser

security:
  - Full_Access_Token: []

paths:
  /api/test:
    post:
      operationId: testCredentials
      summary: Validate Marvin API Credentials
      description: Test the provided Full Access Token for validity.
      security:
        - Full_Access_Token: []
      responses:
        "200":
          description: OK - Valid token
        "401":
          description: Unauthorized - Invalid or missing token

  /api/me:
    get:
      operationId: getUserInfo
      summary: Get User Information
      description: Retrieve information about the logged-in Marvin user.
      security:
        - Full_Access_Token: []
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "401":
          description: Unauthorized - Invalid or missing token
