services:
  datapunk-lake:
    build:
      context: ./datapunk-lake
      dockerfile: Dockerfile
      args:
        PG_MAJOR: ${PG_MAJOR:-16}
        PGVECTOR_VERSION: ${PGVECTOR_VERSION:-0.5.1}
        TIMESCALEDB_VERSION: ${TIMESCALEDB_VERSION:-2}
        POSTGIS_VERSION: ${POSTGIS_VERSION:-3}
    container_name: datapunk_lake
    env_file:
      - .env
      - ./datapunk-lake/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-datapunk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-datapunk}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_archive:/var/lib/postgresql/archive
      - ./datapunk-lake/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./datapunk-lake/config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

volumes:
  postgres_data:
  postgres_archive: