# docker-compose.yml for frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datapunk_frontend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - datapunk_network

networks:
  datapunk_network:
    external: true
