
services:
  postgres:
    image: postgres:latest
    container_name: datapunk_postgres
    environment:
      POSTGRES_USER: datapunk_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: datapunk_db
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - datapunk_network

networks:
  datapunk_network:
    driver: bridge