
services:
  datapunk-lake:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: datapunk
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: datapunk
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U datapunk -d datapunk"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s