x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

services:
  redis:
    image: redis:7-alpine
    container_name: datapunk_redis_cortex
    ports:
      - "6379:6379"
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - datapunk_cortex_network

  datapunk-lake:
    image: datapunk/lake:latest
    container_name: datapunk_lake
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-datapunk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-datapunk}
    volumes:
      - data_volume:/var/lib/postgresql/data
      - import_staging:/data/staging
      - archive:/data/archive
      - lake_logs:/var/log/datapunk/lake
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./config/init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql:ro
    ports:
      - "5432:5432"
    networks:
      - datapunk_cortex_network
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8G'
        reservations:
          cpus: '2'
          memory: '4G'

  datapunk-cortex:
    build:
      context: .
      dockerfile: Dockerfile
    image: datapunk/cortex:latest
    container_name: datapunk_cortex
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      POSTGRES_URL: ${POSTGRES_URL:-postgresql://datapunk:changeme@datapunk-lake:5432/datapunk}
      MODEL_CACHE_SIZE: 2GB
      MAX_BATCH_SIZE: 32
    volumes:
      - cortex_models:/models
      - cortex_cache:/cache
      - cortex_logs:/var/log/datapunk/cortex
    ports:
      - "8001:8001"
    networks:
      - datapunk_cortex_network
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8G'
        reservations:
          cpus: '2'
          memory: '4G'
    depends_on:
      datapunk-lake:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  data_volume:
  import_staging:
  archive:
  lake_logs:
  cortex_models:
  cortex_cache:
  cortex_logs:

networks:
  datapunk_cortex_network:
    driver: bridge